# Generated by Django 4.0.4 on 2022-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('sede', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('obra_social', models.IntegerField()),
                ('sede', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_1', models.CharField(max_length=20)),
                ('especialidad_2', models.CharField(max_length=20)),
                ('nombre_sede', models.CharField(max_length=20)),
            ],
        ),
    ]
