# Generated by Django 4.0.4 on 2022-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='especialidad_1',
            new_name='lugar',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='especialidad_2',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nombre_sede',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(max_length=20),
        ),
    ]
