# Generated by Django 4.0.4 on 2022-06-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludApp', '0002_rename_especialidad_1_sede_lugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente_nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('medico_solicitado', models.CharField(max_length=40)),
                ('sede', models.CharField(max_length=40)),
            ],
        ),
    ]
